### ISSUE TITLE
[QUEST] ID: 467DD8A59876EDFE

### ISSUE THREAD

**Issue by Hal0gen3s** [Frontiers-PackForge/CosmicFrontiers#101]
The game crashes when you look at the recipe by clicking directly on the block shown in the quest

Modpack version: 0.4.0

**Comment by srdr2k3** [comment]
Could you provide the quest name and the chapter instead?

**Comment by Hal0gen3s** [comment]
Chapter: MV "A Crack in the Sky
Quest: Aether Air Distillation
