### ISSUE TITLE
[QUEST] Redstone Dust ×512 is required, but redstone ore is not yielding as much as one would expect

### ISSUE THREAD

**Issue by DreamThorn** [Frontiers-PackForge/CosmicFrontiers#104]
**Describe the bug**
Mining Redstone Ore with the steel mining hammer provides one Raw Redstone which smelts to one pile of Redstone Dust, but the ore itself smelts to 5.  The quest at the end of the intro requires 512 of the dust, which is extreme compared to the other requirements.  This quest is a requirement for the steam age quests, so it is implied that we should achieve this without a macerator.  I tried an ore crushing hammer as well, but it simply destroys the ore; might try again with a higher tier material; the one that I used was iron level.

**Pack Version**
0.4.0 from CurseForge

**Additional context**
I have found possible workarounds:
1. I think it is possible to get into Ars Nouveau this early, so as to get Silk Touch and quintuple the yield.  This is expensive, but less so than finding and mining out a bunch of redstone veins.
2. Vanilla-style enchanting for Silk Touch would be possible if I found two Diamonds in a loot chest.
3. I could make the steam age machines and see if the macerator provides more than one per raw ore, but I don't think it does that in the steam era.  But if it does, I could do it and then pick the machines back up for the quests.  But this makes it even clearer that this is not the intended way.

**Comment by Ghostipedia** [comment]
this is not a bug with frontiers but a bug with Gregtech Modern
