### ISSUE TITLE
[ISSUE] - Luminite ores can be furnaced into ingots

### ISSUE THREAD

**Issue by SunsfuryAlpha** [Frontiers-PackForge/CosmicFrontiers#111]
**Describe the bug**
Whilst Luminite Dust requires an EBF, the raw/crushed/purified/ore block/etc forms can be smelted in a regular furnace

**To Reproduce**
1. Check NEI

**Expected behavior**

**Screenshots/Crash Reports**
![image](https://github.com/Frontiers-PackForge/CosmicFrontiers/assets/15082885/035257af-70db-46d4-a940-28b0effe116c)

**Desktop (please complete the following information):**
 - OS: PC
 - Pack Version 0.4.5b

**Comment by Ghostipedia** [comment]
Thanks for the report! Fortunately doesn't seem to be an issue with frontiers itself, unfortunately it seems to be directly a problem with GregTechModern, Seems any material with the "NO_SMELTING" property is presently not working.

I've gone ahead and forwarded the issue! Cheers!
