### ISSUE TITLE
[ISSUE] - Broken/ inconsistent recipes + other stuff from playtesting

### ISSUE THREAD

**Issue by JuiceyBeans** [Frontiers-PackForge/CosmicFrontiers#115]
Found on Rot playtesting

- [ ] #151
- [x] BoP woods do not follow GT's wood recipes, allowing easy earlygame cheesing
- [ ] #150
- [ ] #149
- [x] Stack upgrade tier 1 and basic tier upgrade conflict (SophStorage)
- [ ] #148
- [ ] #147
- [x] Holystone and Vitrium GT ores have broken textures
- [ ] #146
- [x] Steam Grinders use 8 ore blocks but only output one crushed ore (apparently this is a GTM issue but I'll leave it here anyway)
- [x] Not sure if this is intentional but stripped woods/logs cannot be converted into planks
- [ ] #145
- [ ] #144
- [ ] #122
- [ ] #123
- [ ] #124
- [ ] #125
- [ ] #127
- [ ] #126
- [ ] #128
- [ ] #129
- [ ] #130
- [ ] #131
- [ ] #132
- [ ] #133
- [ ] #134
- [ ] #135
- [ ] #136
- [ ] #138
- [ ] #137
- [ ] #139
- [ ] #140
- [ ] #141
- [ ] #142
- [ ] #143

Not issues but suggestions:
- Would be pretty funny to add all bricks to ``#supplementaries:throwable_bricks`` :trollface:
- Hide cable facades from JEI  
- Some sort of way to create more Seals of the Underworld after the first one would be great for multiplayer
- Probably add GT salt to the tags for Farmer's Delight salt recipes?
- Dark Mode Everywhere button in main menu covers the Forge version and other stuff (bump Y height from 40 to 50 for this, should be in ``darkmodeeverywhere-client.toml``)
- ULV covers would be really good for early game (specifically, for using drums as steam buffers in Steam Age) 
- Purple drink doesn't have any nutrition groups (personally I think this should do Psi) 
- Add Apotheosis gems maybe to suspicious sand/gravel loot tables? Like 4 of us all put ethanol line aside and got sucked into excavating a trail ruin and it would be great to have some sort of reward for that other than vanilla loot
- A way to make more hearts of the sea after finding one? They can only be found in buried treasure loot  which is pretty tedious for the earlygame, especially if you're on a multiplayer server
- A gateway pearl for spirit orbs perhaps? Finding spawners is tedious
- Imo steam machines should do heat too (atleast the boilers)
- /home and /back are unbalanced imo. If you're going to have them be set to as low as 10/30 seconds, its better to just do away with the cooldown at all, as it gets annoying when you have to wait just that 10 seconds or so everytime. That being said, on my survival world, I just make a hole to deepslate and /home back to the top every minute or so to circumvent the breathing mechanics. It just becomes tedious after a while
- Spawn protection would be great, because when you /back to a loaded chunk, you just get instant killed (see: hoglins and brutes)

I'll keep updating this as I find more stuff

**Comment by GirixK** [comment]
Additionally, Treated Wood Sticks have a conflicting recipes with sticks

**Comment by Ghostipedia** [comment]
Iron Furnaces Mod is just borked
I love when GTM changes item names 🥹

**Comment by JuiceyBeans** [comment]
![2024-05-20_18 50 56](https://github.com/Frontiers-PackForge/CosmicFrontiers/assets/75553966/3fecb9a5-e661-411a-8e98-1e33e7bf5415)
My face when CarryOn

**Comment by Ghostipedia** [comment]
I didn't realize how CBT having this all in one issue would be, please in the future make individual issues if possible

**Comment by Ghostipedia** [comment]
@JuiceyBeans 
For Issues :
#134
#139
#144
#149
#151

for #144 in particular it seems to be a mod issue between GTM and something within frontiers, so it might be worth noting to GTM to observe this for natural conflicts as I modifed absolutely nothing kubeside to cause that.
