### ISSUE TITLE
[ISSUE] - Missing items in recipes

### ISSUE THREAD

**Issue by Lolappa** [Frontiers-PackForge/CosmicFrontiers#116]
Some assembler recipes are missing items and can't be crafted

The known recipes with this issue are:
all ME storage component recipes
both create cogwheels

![image](https://github.com/Frontiers-PackForge/CosmicFrontiers/assets/107851895/cc2ffd88-5288-4334-81ff-c0a17551dafb)

**Comment by GirixK** [comment]
In the case of cogwheels, it wants `"4x gtceu:treated_wood_plates"`, when in game it's called `gtceu:treated_wood_plate`

Additionally, this results in the cogwheel recipe cost to stay the same between Crafting and GT Assembler, meaning there's no cost saving benefits of using the assembler recipe, which could be something to consider
