### ISSUE TITLE
Treated sticks conflict with sticks, probably because its part of `#minecraft:planks`

### ISSUE THREAD

**Issue by Ghostipedia** [Frontiers-PackForge/CosmicFrontiers#144]

**Comment by Ghostipedia** [comment]
I have verified nowhere in my scripts I set treated wood planks to have this tag, I'm going to mark this as a mod-conflict with GTM and resolve it manually. Labeling it as a GTM issue as there seems to be plenty of these weird conflicts that are on GTM's side.

**Comment by JuiceyBeans** [comment]
https://github.com/GregTechCEu/GregTech-Modern/issues/1253
