### ISSUE TITLE
[ISSUE] - Breaking cables causes lag

### ISSUE THREAD

**Issue by Lolappa** [Frontiers-PackForge/CosmicFrontiers#154]
Breaking gt cables causes a lot of lag. The amount of lag seems to correspond to the amount of active connections on the cable. Smaller cables also cause more lag.
This also happens on wires but bigger wires cause more lag.

1. Place any gt cable
2. Add connections
3. Break it in survival by hand

![2024-05-24_15 20 27](https://github.com/Frontiers-PackForge/CosmicFrontiers/assets/107851895/bbe5b6ce-776f-46cf-a71e-480e11f31c57)

**Comment by Ghostipedia** [comment]
This is a GT Modern problem, not a CF packside problem, please report it to GTM
