### ISSUE TITLE
[ISSUE] - "Tools fit for survival" wrench task broken

### ISSUE THREAD

**Issue by PurplikDev** [Frontiers-PackForge/CosmicFrontiers#16]
**Describe the bug**
The wrench in the quest
1) Leads to a Smart Filter recipe
2) Doesn't register when a wrench is in the inventory

**To Reproduce**
1. Go to/Unlock "Tools fit for survival" quest
2. Click on Wrench or have a wrench in your inventory

**Expected behavior**
Expected to show a wrench recipe and register a wrench in the player's inventory

**Desktop (please complete the following information):**
 - OS: Win 10
 - Pack Version: 0.1.3-hotfix

**Comment by PurplikDev** [comment]
Found the problem.
The tag of the filter is `ftbfiltersystem:filter": "item_tag(forge:tools/wrench)item_tag(forge:tools/files)`.
You probably accidentally pasted the `item_tag(forge:tools/files)` in there.

**Comment by Ghostipedia** [comment]
Fixed this a few nights at in dev. Just haven't pushed my changes to git yet. Will be fixed next minor patch!
