### ISSUE TITLE
[ISSUE] - Ability to use /gtceu

### ISSUE THREAD

**Issue by stanieldev** [Frontiers-PackForge/CosmicFrontiers#161]
**Describe the bug**
I can use `/gtceu check_recipes_valid` and `/gtceu ui_editor` commands as a non-admin.

**To Reproduce**
1. Be non-admin
2. type `/gtceu` and then autofill

**Expected behavior**
Not being able to change GUIs as a non-admin.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version: 0.4.6.a

**Comment by Ghostipedia** [comment]
GTM issue
