### ISSUE TITLE
mod suggestion

### ISSUE THREAD

**Issue by tjdawngamer** [Frontiers-PackForge/CosmicFrontiers#162]
i think a good mod for the pack is https://www.curseforge.com/minecraft/mc-mods/some-assembly-required for food

**Comment by JuiceyBeans** [comment]
Should be in #3

**Comment by MiyoshiEira** [comment]
Suggestions go into this thread, closing
https://github.com/Frontiers-PackForge/CosmicFrontiers/issues/3
