### ISSUE TITLE
[ISSUE] - Charcoal can be obtained by breaking a campfire

### ISSUE THREAD

**Issue by JuiceyBeans** [Frontiers-PackForge/CosmicFrontiers#165]
Campfires use coal to be crafted, but you can break these to get two bits of charcoal. This may be a feature tbh because the quest mentions that there's a vanilla way to get charcoal other furnace before Coke Oven, but thought I'd mention it anyway

**Comment by srdr2k3** [comment]
This is intended, and a hinted at way to get some early pieces of charcoal.
