### ISSUE TITLE
[ISSUE] - Cannot create superflat world

### ISSUE THREAD

**Issue by TheAlaskanPhysicist** [Frontiers-PackForge/CosmicFrontiers#168]
**Describe the bug**
Every time I try to make a superflat world in the world creation screen, it just makes a default world.

**To Reproduce**
1. Go to create new world
2. Go to the world tab
3. Set it to superflat
4. Create the world

**Expected behavior**
Should be a superflat world.

**Comment by TheAlaskanPhysicist** [comment]
Added information for whoever may work on it, Monifactory seems to have the same problem.
It is likely a shared mod that causes the issue.

**Comment by screret** [comment]
it's a datapack packaged as a mod. namely, terralith.

**Comment by TheAlaskanPhysicist** [comment]
Thank you screret!

**Comment by Ghostipedia** [comment]
Yes due to teralith being needed for other mods or data packs inside of mods it won't be removed, as Superflat worlds are not the focus of Frontiers
Locking this thread after this
