### ISSUE TITLE
[ISSUE] - Add a recipe to repair the respirator

### ISSUE THREAD

**Issue by cherylgames** [Frontiers-PackForge/CosmicFrontiers#170]
add a recipe to refill a respirator such as in your 2by2 in your inventory with the respirator and charcoal

**Comment by nagqu** [comment]
please start using #3 for suggestions

**Comment by srdr2k3** [comment]
#3 is for mod suggestions.

Also make sure to state your pack version and if you are playing on the community server. We have templates for this...
