### ISSUE TITLE
[ISSUE] - Create Copper Backtank loses Cold Sweat insulation when placed on ground

### ISSUE THREAD

**Issue by dandistine** [Frontiers-PackForge/CosmicFrontiers#172]
**Describe the bug**
Placing and then breaking a Create Copper Backtank (probably netherite too) on the ground to recharge will remove any insulation applied from the Cold Sweat mod.

**To Reproduce**
1. Get a Backtank
2. Apply insulation using a sewing table (hoglin hide, waxed leather, etc)
3. Place Backtank on ground
4. Break Backtank with pickaxe
5. Insulation is removed

**Expected behavior**
Insulation is kept.

**Desktop (please complete the following information):**
 - OS: Win11
 - Pack Version 0.4.6a

**Additional context**
The Backtank is generally super convenient for venturing in the Nether due to its ~15 minutes of total air supply.  The QB even recommends that it be made and links it to the Waxed Leather quest as though the expectation is to insulate the Backtank for use in the Nether.

**Comment by Ghostipedia** [comment]
This is not something me or the dev of coldsweat can fix. You'll have to take this issue up with the Create Team directly.
There won't be anything I can fix on this unfortunately, I will however see about adding a passive insulation value to both backtanks. You just won't be able to add your own.
