### ISSUE TITLE
[ISSUE] - Saving REI config crashes the world

### ISSUE THREAD

**Issue by nagqu** [Frontiers-PackForge/CosmicFrontiers#18]
**Describe the bug**
Your game crashes after trying to save changes in them. Set setting are saved.

**To Reproduce**
1. Open the inventory.
2. Click REI settings button.
3. Change any setting.
4. Click "Save & quit" button.
5. Crash.

**Expected behavior**

**Screenshots/Crash Reports**
https://mclo.gs/L2bmtf8
https://mclo.gs/bbOoltC

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Pack Version Current GitHub repo

**Comment by srdr2k3** [comment]
This issue seems to be fixed after updating the pack to 0.2.5.
