### ISSUE TITLE
[ISSUE] - Ender Drawer recipe missing item

### ISSUE THREAD

**Issue by GirixK** [Frontiers-PackForge/CosmicFrontiers#183]
**Describe the bug**
Ender Drawer recipe is missing an item
Specifically '2x gtceu:tungsten_steel_double_plate', classic double plates

**To Reproduce**
1. Check Ender Drawer recipe
2. See poopoo

**Screenshots/Crash Reports**
![image](https://github.com/Frontiers-PackForge/CosmicFrontiers/assets/72603953/043954bc-c5e7-436a-baa8-4fd8b1956f1a)

**Desktop (please complete the following information):**
 - Pack Version 0.4.6-x1

**Comment by srdr2k3** [comment]
Fixed in 0.4.7-dev.
