### ISSUE TITLE
[ISSUE] - ConcurrentModificationException Crash to Desktop

### ISSUE THREAD

**Issue by bfleischhacker** [Frontiers-PackForge/CosmicFrontiers#192]
**Describe the bug**
the game crashed to desktop due to getTemperatureCap

**To Reproduce**
the game just crashed while paused in the background

**Expected behavior**

**Screenshots/Crash Reports**
[crash-2024-08-05_12.51.48-server.txt](https://github.com/user-attachments/files/16501618/crash-2024-08-05_12.51.48-server.txt)

Time: 2024-08-05 12:51:48
Description: Ticking player

**Desktop (please complete the following information):**
 - Pack Version [e.g. 22]

**Additional context**

**Comment by Ghostipedia** [comment]
Please provide your OS and Pack version used
