### ISSUE TITLE
[ISSUE] - no recipes for sophisticated storage and integrated dynamics

### ISSUE THREAD

**Issue by Ximronno** [Frontiers-PackForge/CosmicFrontiers#198]
**Describe the bug**
no recipes for integrated dynamics squeezers , no craft for basic chest to craft other chests in sophisticated storage

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Pack Version [e.g. 22]

**Additional context**
unpleasant experience in early game, you have a lot of resourses, and cannot craft upgraded storage, besides crates, and no early game ae2 like system, for example occultism or integrated dynamics, and also out of context, create seems to be unnecessary, you can use create before gregtech steam age, to be more realistic.

**Comment by mrquentin** [comment]
you can craft the upgrades and upgrade yoour chest that way. also integrated dynamics is not yet implemented in the pack that's why you don't have some recipes.

**Comment by Ghostipedia** [comment]
> **Describe the bug** no recipes for integrated dynamics squeezers , no craft for basic chest to craft other chests in sophisticated storage
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Windows 11
> 
>     * Pack Version [e.g. 22]
> 
> 
> **Additional context** unpleasant experience in early game, you have a lot of resourses, and cannot craft upgraded storage, besides crates, and no early game ae2 like system, for example occultism or integrated dynamics, and also out of context, create seems to be unnecessary, you can use create before gregtech steam age, to be more realistic.

Few things to unpack here so I'll answer each

- Create is a side mod mostly, while it has a little influence on gameplay it's mostly here for a box of redstone gizmos, not to be some arbitrary bad fillin for content prior to steam

- Squeezers will  **never** have a recipe, I unfortunately can't remove recipes *from* the squeezer as the recipes in question are not actual recipes. I will add a tooltip for this.

- This bug report isn't valid, you claim there's no recipes for sophisticated storage, yet there is, please update your pack to 0.5.0 or provide what pack version you are in.
relevant proof recipes exist 
![image](https://github.com/user-attachments/assets/bb28f1c7-46e2-4f73-b583-5c7cc719e47f)
![image](https://github.com/user-attachments/assets/af2cff9f-23a5-494c-a874-6daa8618677f)
![image](https://github.com/user-attachments/assets/6b016367-a91a-47f5-8026-5ab8995241ed)
