### ISSUE TITLE
[QUEST] Hydrochloric Acid Bucket

### ISSUE THREAD

**Issue by Cinobi** [Frontiers-PackForge/CosmicFrontiers#210]
**Describe the bug**
mark in quest doesn't complete quest as it should be

**Expected Information**
Compelte quest fully on questmark

**Screenshots**
![изображение](https://github.com/user-attachments/assets/60936370-b6c0-44dc-80c1-600c6ab45c61) 
![изображение](https://github.com/user-attachments/assets/7d9b187b-b618-4c4a-8603-38bfc5b9f23f)

**Pack Version**
 Curseforge Version
**Additional context**

Let say stright, most of ppl wont craft ir3chlor on their first MV circuit boards its overkill, Better to remove this quest from here atall(or make it fully optional)

**Comment by Ghostipedia** [comment]
Most if not all quests that ask for fluid buckets are meant to be optional.
Ty for catching this 👍
