### ISSUE TITLE
[ISSUE] - Sodium sulfide + CO2 + Quicklime recipe conflict

### ISSUE THREAD

**Issue by triax7** [Frontiers-PackForge/CosmicFrontiers#223]
There are conflicting recipes without circuits:

Sodium sulfide + CO2 + Quicklime
![image](https://github.com/user-attachments/assets/3186cc07-d6d5-444e-b6c3-fe7b55ba7da4)

CO2 + Quicklime
![image](https://github.com/user-attachments/assets/061d3e37-90e9-4d80-90c7-42926c084748)

Idk if that's intended way to do it but I use it to get back soda ash for chromite processing and the conflict is a bit annoying, would be nice to add a circuit to one of the recipes

Pack version: 0.5.2

**Comment by Ghostipedia** [comment]
Recently fixed this! Should be in 0.5.3 or the next major update - I am unsure if I also modified the LCR recipe so I'll keep this open until I can check again
![image](https://github.com/user-attachments/assets/e3021a1c-ce45-4ca8-b946-24b4db97ea4c)

**Comment by Ghostipedia** [comment]
Fixed the LCR Version as well in 28e50e5ab5a1859b781113ecd47219727dbb3583

Closing as this should have resolved the issue now, will be in the release slated for OCT19th
