### ISSUE TITLE
[ISSUE] - no recipe for chromatic floatation plant

### ISSUE THREAD

**Issue by WamenNudles** [Frontiers-PackForge/CosmicFrontiers#229]
recipe is missing/doesnt exist, and no custom multiblock preview

was supposed to be implemented in 5.0

check jei

version 5.2

not urgent

**Comment by Ghostipedia** [comment]
Chromatic Flotation will be added in a future Update (0.6.0) for LUV+ Content
Going to reference back to this issue if another gets opened 👍
