### ISSUE TITLE
[ISSUE] - recipe conflict (wood planks -> boat)

### ISSUE THREAD

**Issue by Quetz4l** [Frontiers-PackForge/CosmicFrontiers#254]
**Describe the bug**
boat recipe without a circuit and this  breaks the crafting of the chest, and other recipes in assembler

**To Reproduce**
put non-vanilla planks in the assembler

**Screenshots/Crash Reports**
![{42A24025-9CB1-4095-97A0-9BC859C3DAD3}](https://github.com/user-attachments/assets/0664d9a2-92f5-428e-8106-63c4292e5f3f)

**Desktop (please complete the following information):**
0.5.5

**Comment by votex09** [comment]
Are you sure you're on 0.5.5?
![image](https://github.com/user-attachments/assets/bf597072-5e4e-4924-a376-c3cfa035cfd7)
