### ISSUE TITLE
[ISSUE] - Recipe: Brewing stand and etc

### ISSUE THREAD

**Issue by Quetz4l** [Frontiers-PackForge/CosmicFrontiers#255]
**Screenshots/Crash Reports**
![{CCD4742A-4E0B-446C-8ED1-820E8AA38D5D}](https://github.com/user-attachments/assets/06a227f9-ae53-4996-aaf2-e8876538ce5e)

Version:
0.5.5

**Comment by Quetz4l** [comment]
![{42180563-1938-49F2-A823-1A19F1E4742E}](https://github.com/user-attachments/assets/5134d428-32aa-4f12-9dcf-ad4a7b7980dc)

**Comment by Quetz4l** [comment]
![{B21C3848-6702-4015-871E-68CB47894CA1}](https://github.com/user-attachments/assets/7c9699d0-615a-4c3b-9a2a-00472e11cf45)

**Comment by Quetz4l** [comment]
![{F41EA77A-2ADC-4B5A-9935-0B38F7AB7B71}](https://github.com/user-attachments/assets/39843899-da6c-4bc1-8318-f0c3bd44bc42)

**Comment by votex09** [comment]
It seems like your install is just borked.
You might have tried to change something within the kubejs files and have an error that's stopping the rest of the files from being read... or, you removed a mod that is mentioned in the kubejs files.

**Comment by Ghostipedia** [comment]
After further investigation, this seems to be a end-user error.
Make sure to fully update your pack, or install a fresh instance and migrate your keybinds/journeymap/settings over appropriately.
