### ISSUE TITLE
[ISSUE] - Conflict(?) between Maple woods from BoP and BWG?

### ISSUE THREAD

**Issue by GirixK** [Frontiers-PackForge/CosmicFrontiers#260]
**Describe the bug**
You can't make any* maple items from BoP's Maple wood, same doesn't apply for BWG's Maple wood

**To Reproduce**
1. Obtain maple logs from BoP
2. Attempt to craft planks
3. See poopoo
4. Sentenced to GregtechWoodOverhaul.js

**Expected behavior**
Being able to use BoP's maple as with any othwer wood

**Desktop (please complete the following information):**
 - Pack Version: 0.5.6

**Comment by Ghostipedia** [comment]
Ended up downgrading BOP
Unfortunately updating BOP seems to cause a lot of damage to worlds, and downgrading it as well seems to cause maple leaves to get destroyed. 

Unfortunately this is the woes of an alpha, i apologize!
