### ISSUE TITLE
[ISSUE] - crash with NullPointerException when spice of life's threshold arrive 10 after eating food

### ISSUE THREAD

**Issue by Watware** [Frontiers-PackForge/CosmicFrontiers#261]
**Describe the bug**

crash when spice of life's threshold arrive 10 after eating food.

it's caused because the mod cold sweat 2.3.10 doesn't has the effect named "cold_sweat:insulated". it was replaced by "cold_sweat:warmth" and "cold_sweat:chill" in recent update of cold sweat.

so just modify `config/solonion.json` can fix this crash i guess. 

**To Reproduce**

eat foods until the threshold arrive 10, then game will crash.

**Expected behavior**

no crash thx ;)

**Screenshots/Crash Reports**
[crash-2024-12-15_01.45.01-server.txt](https://github.com/user-attachments/files/18137199/crash-2024-12-15_01.45.01-server.txt)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Pack Version 0.5.6

**Comment by Ghostipedia** [comment]
Known Issue, 0.5.6 has some really nasty bugs inside of it that have resulted in Coldsweat and a few other mod downgrading.
There is an experimental Branch of 0.5.6 (0.5.6-BE1) in the github releases that will also solve this issue, and help mitigate any other potential problems 0.5.6 has, once I've verified the other big bugs are no longer a problem that experimental branch will roll over to 0.5.7! Thank you for the report regardless and I'll direct others here if it is reported again :)
