### ISSUE TITLE
[ISSUE] - Ars Noveau Novice Spell Book cannot be crafted

### ISSUE THREAD

**Issue by Yeesus** [Frontiers-PackForge/CosmicFrontiers#28]
**Describe the bug**
Novice Spell Book is uncraftable due to requiring the minecraft variant of all tools.
While the pickaxe and axe get crafted as the minecraft version, the shovel and sword are crafted as GregTech tools.

![2023-12-17_13 57 56](https://github.com/Frontiers-PackForge/CosmicFrontiers/assets/93522413/e72f0aef-9e9a-4340-8758-7a1c6f770a57)

**Comment by MiyoshiEira** [comment]
This is getting addressed in the upcoming update, Thanks!
