### ISSUE TITLE
[ISSUE] - GT pipes cannot be placed in water

### ISSUE THREAD

**Issue by Yeesus** [Frontiers-PackForge/CosmicFrontiers#36]
**Describe the bug**
When a GT pipe(fluid or item) is placed in water, both by itself and connected to something, it will immediately "pop" and remove itself, dropping the item on the ground. 

**To Reproduce**
Place a pipe in water

**Expected behavior**
It should not happen

**Desktop (please complete the following information):**
 - OS: windows 10
 - Pack Version : dunno exactly but contains exactly 1 LV quest

**Comment by MiyoshiEira** [comment]
If possible please submit a screenshot where you’re experiencing the issue so we have some more info to go on for more accurate troubleshooting

**Comment by MiyoshiEira** [comment]
Just looking at it and using the minecraft screenshot (F2) would be great just so we’ve got something visual to go on

**Comment by Ghostipedia** [comment]
This is not a pack issue, please report this to GT:Modern's github.

https://github.com/GregTechCEu/GregTech-Modern
