### ISSUE TITLE
Laugh At Ghost's Quest Mistakes  (Quest MegaThread)

### ISSUE THREAD

**Issue by Ghostipedia** [Frontiers-PackForge/CosmicFrontiers#5]
Please Format your quest issue as follows

Quest Chapter :
Quest Name :
Issue Described : 

Please Make these Task lists by clicking this icon and using this formatting
![image](https://github.com/Ghostipedia/CosmicFrontiers/assets/46772882/6c30bf0e-2136-49d6-bbf0-e47578584765)

**Comment by srdr2k3** [comment]
Quest Chapter: First Steps
Quest Name: Get Some Bi- I mean Wood / FTB:Ultimine and You
Issue: FTB:Ultimine should be instead FTB: Ultimine

**Comment by srdr2k3** [comment]
Quest Chapter: First Steps
Quest Name: Tools fit for survival
Issues: 
- [ ] Hammers fare -> Hammer are
- [ ] Wrenches… gregtech -> GregTech
- [ ] Wire Cutters …cables.q6 -> cables.

**Comment by pani29** [comment]
Quest Chapter : Rising Pressure
Issue Described : Add a quest that tells people to go to shipwrecks to find iron ingots.

**Comment by Ghostipedia** [comment]
> Quest Chapter : Rising Pressure Issue Described : Add a quest that tells people to go to shipwrecks to find iron ingots.

It's unintentional behavior, will be fixed in 0.2.0

**Comment by srdr2k3** [comment]
Quest Chapter: First Steps
Quest Name: FTB: Ultimine and You
Issue:
- [ ] The Smart filter tag is set to logs, should be set to raw ore instead

**Comment by HelpMySpacebarBroke** [comment]
Quest Chapter: Rising Pressure [Steam]
Quest Name: Coke Oven Brick/Compressed Coke Clay
Issue Described: Coke oven brick (the cooked material) is the first quest in order, while the raw product is the immidiately following quest 
(Screenshot) 
![image](https://github.com/Frontiers-PackForge/CosmicFrontiers/assets/85506340/58a3cac7-a446-4746-a0f8-de02d959a746)

**Comment by srdr2k3** [comment]
Quest Chapter: Turn On the Lights
Quest Name: Basic Alloy Smelter
Issues:
- [ ] Typo in description (Cupronickle -> Cupronickel).
- [ ] It really should not be gating the Cupronickel Coil quest imo.

**Comment by srdr2k3** [comment]
Quest Chapter: Turn On the Lights
Quest Name: Basic Extractor
Issues:
- [ ] Same Issue with the Alloy Smelter quest. It really shouldn't be gating the Cupronickel Coil quest

**Comment by srdr2k3** [comment]
Quest Chapter: Turn On the Lights
Quest Name: Power of a Mage
Issues: 
- [ ] Quest is missing its description

**Comment by srdr2k3** [comment]
Quest Chapter: Turn On the Lights
Quest Name: Basic Mixer
Issues:
- [ ] Has the Mechanical Mixer quest as its dependency, but has nothing to do with said quest.

**Comment by srdr2k3** [comment]
Quest Chapter: Turn On the Lights (LV)
Quest Name: Blue Alloy Dust
Issues:
- [ ] The quest should be optional. Blue Alloy also has an Alloy Smelter recipe.

**Comment by srdr2k3** [comment]
Quest Chapter: Turn On the Lights (LV)
Quest Name: Nether Sediment Sludge Bucket
Issues:
- [ ] The quest is a dependency for the blackstone pustule quest. Should be the reverse.

**Comment by Ghostipedia** [comment]
> Quest Chapter: Turn On the Lights (LV) Quest Name: Nether Sediment Sludge Bucket Issues:
> 
>     * [ ]  The quest is a dependency for the blackstone pustule quest. Should be the reverse.

This is inententional



> Quest Chapter: Turn On the Lights (LV) Quest Name: Blue Alloy Dust Issues:
> 
>     * [ ]  The quest should be optional. Blue Alloy also has an Alloy Smelter recipe.

Alloy smelter recipe should be removed and replaced with an EBF recipe @Ghostipedia Reminder for later

**Comment by Ghostipedia** [comment]
Deprecated - Use The new Quest Book Bug Issue
![image](https://github.com/Frontiers-PackForge/CosmicFrontiers/assets/46772882/e43c1004-810d-4441-a1be-550898b71cbc)

I thought a thread would be easier to keep track of, but it was, in fact, not.
