### ISSUE TITLE
[ISSUE] - Steel has no GT machine recipes

### ISSUE THREAD

**Issue by WaterShines123** [Frontiers-PackForge/CosmicFrontiers#53]
**Describe the bug**
No lathe, bender forge hammer extruder etc recipes available for steel

**To Reproduce**
See steel recipes in REI

**Expected behavior**
Should have auto generated GT machine recipes

**Desktop (please complete the following information):**
 - OS: [MACOS]
 - Pack Version [0.2.0 CF]

**Comment by srdr2k3** [comment]
Huh, seems like REI doesn't show the recipes that has steel ingot as a input.
I can confirm that the recipes work as normal in their respective machines though.

**Comment by WaterShines123** [comment]
Fair enough then well that is weird

**Comment by Ghostipedia** [comment]
> Huh, seems like REI doesn't show the recipes that has steel ingot as a input. I can confirm that the recipes work as normal in their respective machines though.

I have confirmed the error originates from our KubeJS folder, I'll be doing a deep dive into it after I'm a bit more free today

**Comment by srdr2k3** [comment]
Fixed by #54
