### ISSUE TITLE
[ISSUE] - Crusher Spirits yield Barrier Blocks as Output

### ISSUE THREAD

**Issue by BestMod** [Frontiers-PackForge/CosmicFrontiers#85]
**Describe the bug**
crusher spirits give barriers :)

**To Reproduce**
1. make crusher spirit
2. give any crushable material
3. profit

**Expected behavior**
not that

**Screenshots/Crash Reports**

**Desktop (please complete the following information):**
no

**Additional context**
crubsh

**Comment by srdr2k3** [comment]
Okay my knowledge in Java and Modding is really bad, so take it with a grain of salt. But I took a look at [Occultism's code for crusher recipes](https://github.com/klikli-dev/occultism/blob/version/1.20.1/src/generated/resources/data/occultism/recipes/crushing/iridium_dust_from_ingot.json) 
It seems like the crusher is trying to output anything with the tag "forge:dusts/(product)". Still have no idea why this would yield in Barrier Blocks though, all the dusts seem to have "forge:dusts/" tag, so it should work in theory.

Is it possible that it is on Occultism's end? I remember seeing something similar in ATM9 as well.
![image](https://github.com/Frontiers-PackForge/CosmicFrontiers/assets/99605300/25d9e35d-5d1c-4405-b86b-843088f78690)
![image](https://github.com/Frontiers-PackForge/CosmicFrontiers/assets/99605300/759f70c4-b7f3-4f9a-a27e-f5f5c226bac7)

**Comment by Ghostipedia** [comment]
> Okay my knowledge in Java and Modding is really bad, so take it with a grain of salt. But I took a look at [Occultism's code for crusher recipes](https://github.com/klikli-dev/occultism/blob/version/1.20.1/src/generated/resources/data/occultism/recipes/crushing/iridium_dust_from_ingot.json) It seems like the crusher is trying to output anything with the tag "forge:dusts/(product)". Still have no idea why this would yield in Barrier Blocks though, all the dusts seem to have "forge:dusts/" tag, so it should work in theory.
> 
> Is it possible that it is on Occultism's end? I remember seeing something similar in ATM9 as well. ![image](https://private-user-images.githubusercontent.com/99605300/303108450-25d9e35d-5d1c-4405-b86b-843088f78690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMzM3MjMsIm5iZiI6MTcwNzMzMzQyMywicGF0aCI6Ii85OTYwNTMwMC8zMDMxMDg0NTAtMjVkOWUzNWQtNWQxYy00NDA1LWI4NmItODQzMDg4Zjc4NjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE5MTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYTUzYTBlYzZkODNiNzAyZjUzOGMzYmE0ZDM5MDdmODU2Y2YwNWJmZTVlMjcwNDMxYjE5MGI4MmFlNzY2NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qcVhSsBbcOF_uP7cMgfSL4V06XjOXXmKhxwRXikqAFo) ![image](https://private-user-images.githubusercontent.com/99605300/303108544-759f70c4-b7f3-4f9a-a27e-f5f5c226bac7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMzM3MjMsIm5iZiI6MTcwNzMzMzQyMywicGF0aCI6Ii85OTYwNTMwMC8zMDMxMDg1NDQtNzU5ZjcwYzQtYjdmMy00ZjlhLWEyN2UtZjVmNWMyMjZiYWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE5MTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZTQyZWQyODQ0OWRkOWQ3NDg3ZmNmZDM4MTU4ZmY3NmQ2ZjdiNjhiNDJjMDcxNWY0NWYxZDMyY2ZjMmIyMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aeVwCQZV0edpfUDZl8yHKLpDVddYupSeysIQ5NjY8yM)

Due to the Nature of Frontiers, none of this recipes will exist to begin with, this report is to remind me to purge all Occultism recipes for 0.3.2, as well as other mods that are considered "NYI"

**Comment by Ghostipedia** [comment]
All Occultism Recipes have now been disabled with de84ea79d0c3324933f0235cbd824e44cfa5b5a9
