### ISSUE TITLE
[ISSUE] - Missing lang file entries

### ISSUE THREAD

**Issue by WaterShines123** [Frontiers-PackForge/CosmicFrontiers#88]
All Chemical dehydrators plus the recipe type

All laminators plus recipe type

All Tempering autoclaves

Nether catalyzer recipe type

Flora Nurturer recipe type

Mana fluidizer recipe type

Sorry didn't want to make an official issue out of this but thought the best way to report it idm writing them myself if you want me to 
@Watershines

**Comment by srdr2k3** [comment]
This has been long fixed
