### ISSUE TITLE
[ISSUE] - Sodium Carbonate missing texture

### ISSUE THREAD

**Issue by srdr2k3** [Frontiers-PackForge/CosmicFrontiers#96]
Not sure if it had a texture before.
![image](https://github.com/Frontiers-PackForge/CosmicFrontiers/assets/99605300/71b4f013-5ebd-4af3-a570-1c52fa0daaaf)

Version: 0.4.0, and the commits after it.

**Comment by Ghostipedia** [comment]
Fixed with 4703b9f
