### ISSUE TITLE
[ISSUE] - LV Laminator not working 

### ISSUE THREAD

**Issue by WaterShines123** [Frontiers-PackForge/CosmicFrontiers#97]
**Describe the bug**
Laminator does not make me cable

**Screenshots/Crash Reports**
![2024-04-12_23 32 28](https://github.com/Frontiers-PackForge/CosmicFrontiers/assets/129415710/2fc4562e-70c5-4143-ba94-f64ba9d45cef)

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Pack Version [0.4.0]

**Comment by srdr2k3** [comment]
Seems like the fluid inputs for the cables are broken in Ae2_Mods.js

**Comment by Ghostipedia** [comment]
Fixed In dev
